-- CREATE TABLE PRODUCT (
-- 	ID INT PRIMARY KEY,
-- 	PRODUCT_NAME TEXT NOT NULL,
-- 	CATEGORY TEXT NOT NULL,
-- 	PRICE FLOAT NOT NULL
-- )

-- INSERT INTO
-- 	PRODUCT (ID, PRODUCT_NAME, CATEGORY, PRICE)
-- VALUES
-- 	(1, 'IPHONE', 'PHONES', 8000),
-- 	(2, 'UB RELAXER', 'COSMETICS', 850),
-- 	(3, 'AKAI FAN', 'ELECTRONICS', 900),
-- 	(4, 'IPHONE 14', 'PHONES', 4000),
-- 	(5, 'GAS STOVE', 'HOME APPLIANCE', 8999.99)


-- CREATE TABLE SALES (
-- 	ID INT PRIMARY KEY,
-- 	PRODUCT_ID VARCHAR(10) NOT NULL,
-- 	QUANTITY_SOLD INT,
-- 	SALE_DATE DATE,
-- 	TOTAL_PRICE FLOAT
-- )


-- INSERT INTO
-- 	SALES (ID, PRODUCT_ID, QUANTITY_SOLD, SALE_DATE, TOTAL_PRICE)
-- VALUES
-- 	(1, 'APPL1', 1, '2025-03-06', 80000),
-- 	(2, 'COSM1', 1, '2025-03-06',  850),
-- 	(3, 'ELEC1', 0, '2025-03-06', 0),
-- 	(4, 'APPL2', 0, '2025-03-06', 0),
-- 	(5, 'HOAP1', 1, '2025-03-06', 8999.99)

-- SELECT * FROM PRODUCT

-- SELECT PRODUCT_NAME, PRICE FROM PRODUCT


-- SELECT * FROM SALES LIMIT	2

-- SELECT * FROM SALES
-- WHERE TOTAL_PRICE > 100

-- SELECT * FROM PRODUCT
-- WHERE CATEGORY = 'PHONES'

-- SELECT COUNT(*) FROM PRODUCT

-- SELECT SUM(TOTAL_PRICE) AS TOTAL_PRICE
-- FROM SALES

-- SELECT AVG(PRICE) AS PRICE
-- FROM PRODUCT








