# Generated by Django 5.1.7 on 2025-04-10 17:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_remove_myemployee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myemployee',
            name='user',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='myemployee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
