# Generated by Django 5.1.7 on 2025-04-11 06:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_myemployer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(blank=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('remote', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joblisting', to='job_app.myemployer')),
            ],
        ),
    ]
