# Generated by Django 5.1.7 on 2025-04-12 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_jobapplication_jobposting_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='job_app.myemployee')),
            ],
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='job_app.jobposting'),
        ),
    ]
