# Generated by Django 5.1.7 on 2025-04-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_jobapplications_delete_jobapplication_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplications',
            new_name='JobApplication',
        ),
    ]
