# Generated by Django 5.1.7 on 2025-04-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_rename_jobapplications_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
