# Generated by Django 5.1.7 on 2025-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0010_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.TextField(default='No resume'),
            preserve_default=False,
        ),
    ]
