# Generated by Django 5.1.7 on 2025-04-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0011_jobapplication_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='created_at',
        ),
    ]
