# Generated by Django 5.1.7 on 2025-04-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0015_alter_jobposting_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='deadline',
        ),
    ]
