# Generated by Django 5.1.7 on 2025-04-12 10:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0018_alter_jobposting_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='poster',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='job_app.myemployer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 7, 11, 10, 2, 48, 818512, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
