# Generated by Django 5.1.7 on 2025-04-12 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0019_jobapplication_poster_alter_jobposting_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='poster',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 7, 11, 10, 34, 55, 690749, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
